USE master
GO
IF EXISTS (SELECT * FROM sys.databases WHERE NAME ='QUANLYSHOPGIAY')
DROP DATABASE QUANLYSHOPGIAY
GO

CREATE DATABASE QUANLYSHOPGIAY
GO

USE QUANLYSHOPGIAY

GO

CREATE TABLE COLORS(
	ID INT IDENTITY (1,1) NOT NULL,
	NAMEE NVARCHAR(60),
	CODECOLOR CHAR(3) NOT NULL,
	STATUSS BIT
)--1

ALTER TABLE COLORS
ADD
	CONSTRAINT PK_COLORS_ID PRIMARY KEY (ID),
	CONSTRAINT CHK_COLORS_CODECOLOR CHECK(CODECOLOR NOT LIKE '% %'),
	CONSTRAINT UQ_COLORS_CODECOLOR UNIQUE(CODECOLOR),
	CONSTRAINT DE_COLORS_STATUSS DEFAULT '0' FOR STATUSS
GO

CREATE TABLE SIZES(
	ID INT IDENTITY (1,1),
	SIZES SMALLINT,
	DETAIL NVARCHAR(20),
	STATUSS BIT,
)--2
ALTER TABLE SIZES
ADD
	CONSTRAINT PK_SIZES_ID PRIMARY KEY (ID),
	CONSTRAINT CHK_SIZES_CODECOLOR CHECK(CODECOLOR NOT LIKE '% %'),
	CONSTRAINT DE_SIZES_STATUSS DEFAULT '0' FOR STATUSS
GO


CREATE TABLE TRADEMARK(
	ID INT IDENTITY(1,1),
	NAMEE NVARCHAR(20),
	STATUSS BIT
)--3
ALTER TABLE TRADEMARK
ADD
	CONSTRAINT PK_TRADEMARK_ID PRIMARY KEY (ID),
	CONSTRAINT DE_TRADEMARK_STATUSS DEFAULT '0' FOR STATUSS
GO

CREATE TABLE CATEGORIES(
	ID INT IDENTITY(1,1),
	NAMEE NVARCHAR(20),
	STATUSS BIT
)--4
ALTER TABLE CATEGORIES
ADD
	CONSTRAINT PK_CATEGORIES_ID PRIMARY KEY (ID),
	CONSTRAINT DE_CATEGORIES_STATUSS DEFAULT '0' FOR STATUSS
GO

CREATE TABLE SHIP(
	ID INT IDENTITY(1,1),
	NAMEE NVARCHAR(20),
	STATUSS BIT
)--5
ALTER TABLE SIZES
ADD
	CONSTRAINT PK_SHIP_ID PRIMARY KEY (ID),
	CONSTRAINT DE_SHIP_STATUSS DEFAULT '0' FOR STATUSS
GO

CREATE TABLE PROVINCES(
	ID INT IDENTITY(1,1),
	NAMEE NVARCHAR(20)
)--6
ALTER TABLE PROVIENCES
ADD
	CONSTRAINT PK_PROVINCES_ID PRIMARY KEY (ID)
GO

CREATE TABLE DISTRICTS(
	ID INT IDENTITY(1,1),
	NAMEE NVARCHAR(20),
	ID_PROVINCES INT
)--7
ALTER TABLE DISTRICTS
ADD
	CONSTRAINT PK_DISTRICTS_ID PRIMARY KEY (ID),
	CONSTRAINT FK_PROVINCES_DISTRICTS_ID_PROVINCES FOREIGN KEY(ID_PROVINCES) REFERENCES PROVINCES(ID) ON UPDATE CASCADE ON DELETE CASCADE
GO

CREATE TABLE COMMUNES(
	ID INT IDENTITY(1,1),
	NAMEE NVARCHAR(20),
	ID_DISTRICTS INT
)--8
ALTER TABLE COMMUNES
ADD
	CONSTRAINT PK_COMMUNES_ID PRIMARY KEY (ID),
	CONSTRAINT FK_DISTRICTS_COMMUNES_ID_DISTRICTS FOREIGN KEY(ID_DISTRICTS) REFERENCES DISTRICTS(ID) ON UPDATE CASCADE ON DELETE CASCADE
GO

CREATE TABLE ADDRESSS(
	ID INT IDENTITY(1,1),
	ID_COMMUNES INT,
	DETAIL NVARCHAR(20)
)--9
ALTER TABLE DISTRICTS
ADD
	CONSTRAINT PK_ADDRESSS_ID PRIMARY KEY (ID),
	CONSTRAINT FK_COMMUNES_ADDRESSS_ID_COMMUNES FOREIGN KEY(ID_COMMUNES) REFERENCES ADDRESSS(ID) ON UPDATE CASCADE ON DELETE CASCADE
GO

CREATE TABLE ACCOUNT(
	ID INT IDENTITY(1,1),
	NAMEE NVARCHAR(20),
	IMAGEE NVARCHAR(20),
	EMAIL VARCHAR(30),
	PHONE CHAR(10),
	STATUSS BIT,
	ID_ADDRESS INT
)--10
ALTER TABLE ACCOUNT 
ADD
	CONSTRAINT PK_ACCOUNT_ID PRIMARY KEY (ID),
	CONSTRAINT FK_ADDRESSS_ACCOUNT_ID_ADDRESSS FOREIGN KEY(ID_ADDRESSS) REFERENCES ADDRESSS(ID) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT DE_ACCOUNT_STATUSS DEFAULT '0' FOR STATUSS,
	CONSTRAINT CHK_ADDRESSS_EMAIL CHECK(EMAIL IN ('[a-z]%@gmail.@','[a-z]%@ute.udn.vn','[a-z]%@mail.yahoo.com','[a-z]%@%.%') AND EMAIL NOT LIKE '[% %]'),
	CONSTRAINT CHK_ADDRESSS_PHONE CHECK(PHONE LIKE '0[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]')
GO

CREATE TABLE STATUS_BILLS(
	ID INT IDENTITY(1,1),
	SUCCESS BIT,
	ERORR BIT,
	TRANSPORTING BIT,
	PREPARING BIT
)--11
ALTER TABLE STATUS_BILLS
ADD
	CONSTRAINT PK_STATUS_BILLS_ID PRIMARY KEY (ID),
	CONSTRAINT DE_STATUS_BILLS_PREPARING DEFAULT '0' FOR PREPARING
	
GO

CREATE TABLE SELLS_VOUCHER(
	ID CHAR(10),
	NAMEE NVARCHAR(30),
	EMAIL VARCHAR(20),
	PHONE CHAR(10),
	ID_ADDRESS INT
)--12
ALTER TABLE SELLS_VOUCHER
ADD
	CONSTRAINT PK_SELLS_VOUCHER_ID PRIMARY KEY (ID),
	CONSTRAINT FK_ADDRESSS_SELLS_VOUCHER_ID_ADDRESSS FOREIGN KEY(ID_ADDRESSS) REFERENCES ADDRESSS(ID) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT CHK_SELLS_VOUCHER_EMAIL CHECK(EMAIL IN ('[a-z]%@gmail.@','[a-z]%@ute.udn.vn','[a-z]%@mail.yahoo.com','[a-z]%@%.%') AND EMAIL NOT LIKE '[% %]'),
	CONSTRAINT CHK_SELLS_VOUCHER_PHONE CHECK(PHONE LIKE '0[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]')
GO

CREATE TABLE SHOES(
	ID INT IDENTITY(1,1),
	NAMEE NVARCHAR(40),
	DETAIL NVARCHAR(20),
	STATUSS BIT,
	ID_TRADEMARK INT
)--13
ALTER TABLE SHOES
ADD
	CONSTRAINT PK_SHOES_ID PRIMARY KEY (ID),
	CONSTRAINT FK_TRADEMARK_SHOES_ID_TRADEMARK FOREIGN KEY(ID_TRADEMARK) REFERENCES TRADEMARK(ID) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT DE_ACCOUNT_STATUSS DEFAULT '0' FOR STATUSS
GO
----------------------------------------
CREATE TABLE DETAIL_SHOES(
	ID INT IDENTITY(1,1),
	ID_SHOE INT,
	PRICE MONEY,
	COUNTT INT,
	STATUSS BIT
)--14
GO

CREATE TABLE DETAIL_COLORS(
	ID_DETAIL_SHOE INT,
	ID_COLOR INT
)--15
GO

CREATE TABLE DETAI_SIZES(
	ID_DETAIL_SHOE INT,
	ID_SIZE INT
)--16
GO

CREATE TABLE NOTIFICATIONN(
	ID INT IDENTITY(1,1),
	DETAIL NVARCHAR(20),
	SEEN BIT,
	ID_ACCOUNT INT
)--17
GO

CREATE TABLE COMMENT_REVIEW(
	ID INT IDENTITY(1,1),
	RATE SMALLINT,
	DETAIL NVARCHAR(20),
	ID_DETAIL_SHOE INT,
	ID_ACCOUNT INT	
)--18
GO

CREATE TABLE DETAIL_CATEGORIES(
	ID_CATEGOTIES INT,
	ID_SHOES INT
)--19
GO

CREATE TABLE USERMANAGER(
	ID INT IDENTITY(1,1),
	NAMEE NVARCHAR(30),
	EMAIL VARCHAR(20),
	PHONE CHAR(10),
	ID_IMAGE VARCHAR,
	ID_ADDRESS INT
)--20
GO

CREATE TABLE STAFFS(
	ID INT IDENTITY(1,1),
	NAMEE NVARCHAR(30),
	DATEOFBIRTH DATE,
	EMAIL VARCHAR(20),
	PHONE CHAR(20),
	ID_IMAGE VARCHAR,
	ID_ADDRESS INT
)--21
GO

CREATE TABLE IMAGES(
	ID VARCHAR(20), --URL
	ID_DETAIL_SHOES INT
)--22
GO

CREATE TABLE CART(
	ID_ACCOUNT INT,
	ID_DETAIL_SHOE INT
)--23
GO

CREATE TABLE BILLS(
	ID INT IDENTITY(1,1),
	DATECHECKIN DATE,
	DATECHECKOUT DATE,
	NOTE NVARCHAR(20),
	PAYMENT_METHODS BIT,
	ID_ACCOUNT INT,
	ID_ADDRESS INT,
	ID_SHIP INT,
	ID_SELL_VOUCHER CHAR(10),
	ID_STAFF INT,
	ID_STATUS SMALLINT
)--24
GO

CREATE TABLE DETAIL_BILLS(
	ID INT IDENTITY(1,1),
	ID_BILLS INT,
	ID_DETAIL_SHOES INT,
	COUNTT SMALLINT,
	PRICE MONEY
)--25
--RÀNG BUỘC